# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve -l -H localhost`. If you change this file, please restart theÂ 
# server process.

# Basic Site Settings
localeÂ  Â  Â  Â  Â  Â  Â  Â  Â  Â : "en-US"
site_themeÂ  Â  Â  Â  Â  Â  Â  Â : "default"
titleÂ  Â  Â  Â  Â  Â  Â  Â  Â  Â  : "Zhaoyu Xing / é‚¢ç…§å®‡"
title_separatorÂ  Â  Â  Â  Â  : "-"
nameÂ  Â  Â  Â  Â  Â  Â  Â  Â  Â  Â : &name "Zhaoyu Xing"
descriptionÂ  Â  Â  Â  Â  Â  Â  : &description "Postdoctoral Research Associate in Statistics"
urlÂ  Â  Â  Â  Â  Â  Â  Â  Â  Â  Â  : https://ZhaoyuXingStat.github.io # the base hostname & protocol for your site e.g. "https://[your GitHub username].github.io" or if you already have some other page hosted on Github then use "https://[your GitHub username].github.io/[Your Repo Name]"
baseurlÂ  Â  Â  Â  Â  Â  Â  Â  Â  : "" # the subpath of your site, e.g. "/blog"
repositoryÂ  Â  Â  Â  Â  Â  Â  Â : "ZhaoyuXingStat/ZhaoyuXingStat.github.io"

# Site Author - The following control what appear as part of the author content on the side bar.
#Â  Â  Â  Â  Â  Â  Â  Â If a field is blank the icon and link will not appear, otherwise it will be shown.
#Â  Â  Â  Â  Â  Â  Â  Â Additional customization can be done by editing /_includes/author-profile.html
author:
Â  # Biographic information
Â  avatarÂ  Â  Â  Â  Â  Â : "profile.jpg"
Â  nameÂ  Â  Â  Â  Â  Â  Â : "Zhaoyu Xing"
Â  pronounsÂ  Â  Â  Â  Â : # "he/him"Â Â 
Â  bioÂ  Â  Â  Â  Â  Â  Â  : "Statistics Ph.D. from Xiamen University. Passionate about guitar ğŸ¸, milk tea ğŸµ, and occasionally doing some statistics ğŸ“Š."
Â  locationÂ  Â  Â  Â  Â : "South Bend, Indiana"
Â  employerÂ  Â  Â  Â  Â : "University of Notre Dame"
Â  uriÂ  Â  Â  Â  Â  Â  Â  : # "https://zenghao-stat.github.io"
Â  emailÂ  Â  Â  Â  Â  Â  : "your-email@example.com" # <-- è¯·æ›¿æ¢æˆä½ çš„é‚®ç®±

Â  # Academic websites
Â  academiaÂ  Â  Â  Â  Â : # URL
Â  arxivÂ  Â  Â  Â  Â  Â  : # URL - Update with the correct link to your profile
Â  googlescholarÂ  Â  : # "https://scholar.google.com/citations?user=your-id" <-- è¯·æ›¿æ¢æˆä½ çš„è°·æ­Œå­¦æœ¯é“¾æ¥
Â  impactstoryÂ  Â  Â  : # URL
Â  orcidÂ  Â  Â  Â  Â  Â  : # "http://orcid.org/yourorcidurl"
Â  semanticÂ  Â  Â  Â  Â : # URL
Â  pubmedÂ  Â  Â  Â  Â  Â : # "https://www.ncbi.nlm.nih.gov/pubmed/?term=john+snow"
Â  researchgateÂ  Â  Â : # URL
Â  scopusÂ  Â  Â  Â  Â  Â : # URL

Â  # Repositories and software development
Â  bitbucketÂ  Â  Â  Â  : # Username - Update with your username on the site
Â  codepenÂ  Â  Â  Â  Â  : # Username
Â  dribbbleÂ  Â  Â  Â  Â : # Username
Â  githubÂ  Â  Â  Â  Â  Â : "ZhaoyuXingStat"
Â  kaggleÂ  Â  Â  Â  Â  Â : # UsernameÂ Â 
Â  stackoverflowÂ  Â  : # User number or user number and name (i.e., use "1" or "1/jeff-atwood")Â  Â Â 

Â  # Social media
Â  blueskyÂ  Â  Â  Â  Â  : # "bsky.app" # Replace this with you Bluesky username
Â  facebookÂ  Â  Â  Â  Â : # Username
Â  flickrÂ  Â  Â  Â  Â  Â : # Username
Â  foursquareÂ  Â  Â  Â : # Username
Â  goodreadsÂ  Â  Â  Â  : # Username
Â  google_plusÂ  Â  Â  : # Username
Â  keybaseÂ  Â  Â  Â  Â  : # Username
Â  instagramÂ  Â  Â  Â  : # Username
Â  lastfmÂ  Â  Â  Â  Â  Â : # Username
Â  linkedinÂ  Â  Â  Â  Â : # your-linkedin-username <-- è¯·æ›¿æ¢æˆä½ çš„é¢†è‹±ç”¨æˆ·å
Â  mastodonÂ  Â  Â  Â  Â : # URL
Â  mediumÂ  Â  Â  Â  Â  Â : # URL
Â  pinterestÂ  Â  Â  Â  : # Username
Â  soundcloudÂ  Â  Â  Â : # Username
Â  steamÂ  Â  Â  Â  Â  Â  : # Username
Â  telegramÂ  Â  Â  Â  Â : # URL
Â  tumblrÂ  Â  Â  Â  Â  Â : # Username
Â  twitterÂ  Â  Â  Â  Â  : # Username for X / Twitter
Â  vineÂ  Â  Â  Â  Â  Â  Â : # Username
Â  weiboÂ  Â  Â  Â  Â  Â  : # Username
Â  wikipediaÂ  Â  Â  Â  : # Username
Â  xingÂ  Â  Â  Â  Â  Â  Â : # Username
Â  youtubeÂ  Â  Â  Â  Â  : # Username
Â  zhihuÂ  Â  Â  Â  Â  Â  : # Username

# Publication Category - The following the list of publication categories and their headings
publication_category:
Â  books:
Â  Â  title: 'Books'
Â  manuscripts:
Â  Â  title: 'Journal Articles'Â  Â Â 
Â  conferences:
Â  Â  title: 'Conference Papers'

# Site Settings
teaserÂ  Â  Â  Â  Â  Â  Â  Â  Â  Â :Â  # filename of teaser fallback teaser image placed in /images/, .e.g. "500x300.png"
breadcrumbsÂ  Â  Â  Â  Â  Â  Â  : false # true, false (default)
words_per_minuteÂ  Â  Â  Â  Â : 160
futureÂ  Â  Â  Â  Â  Â  Â  Â  Â  Â : true
read_moreÂ  Â  Â  Â  Â  Â  Â  Â  : "disabled" # if enabled, adds "Read more" links to excerpts
talkmap_linkÂ  Â  Â  Â  Â  Â  Â : falseÂ  Â  Â  #change to true to add link to talkmap on talks page
comments:
Â  providerÂ  Â  Â  Â  Â  Â  Â  Â : # false (default), "disqus", "discourse", "facebook", "google-plus", "staticman", "custom"
Â  disqus:
Â  Â  shortnameÂ  Â  Â  Â  Â  Â  :
Â  discourse:
Â  Â  serverÂ  Â  Â  Â  Â  Â  Â  Â : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
Â  facebook:
Â  Â  appidÂ  Â  Â  Â  Â  Â  Â  Â  :
Â  Â  num_postsÂ  Â  Â  Â  Â  Â  : # 5 (default)
Â  Â  colorschemeÂ  Â  Â  Â  Â  : # "light" (default), "dark"
staticman:
Â  allowedFieldsÂ  Â  Â  Â  Â  : ['name', 'email', 'url', 'message']
Â  branchÂ  Â  Â  Â  Â  Â  Â  Â  Â : "gh-pages" # "master", "gh-pages"
Â  commitMessageÂ  Â  Â  Â  Â  : "New comment."
Â  filenameÂ  Â  Â  Â  Â  Â  Â  Â : comment-{@timestamp}
Â  formatÂ  Â  Â  Â  Â  Â  Â  Â  Â : "yml"
Â  moderationÂ  Â  Â  Â  Â  Â  Â : true
Â  pathÂ  Â  Â  Â  Â  Â  Â  Â  Â  Â : "_data/comments/{options.slug}"
Â  requiredFieldsÂ  Â  Â  Â  Â : ['name', 'email', 'message']
Â  transforms:
Â  Â  emailÂ  Â  Â  Â  Â  Â  Â  Â  : "md5"
Â  generatedFields:
Â  Â  date:
Â  Â  Â  typeÂ  Â  Â  Â  Â  Â  Â  Â : "date"
Â  Â  Â  options:
Â  Â  Â  Â  formatÂ  Â  Â  Â  Â  Â : "iso8601" # "iso8601" (default), "timestamp-seconds", "timestamp-milliseconds"
atom_feed:
Â  hideÂ  Â  Â  Â  Â  Â  Â  Â  Â  Â : trueÂ  Â  Â # change to true to hide the RSS feed in the footer
Â  pathÂ  Â  Â  Â  Â  Â  Â  Â  Â  Â : # blank (default) uses feed.xml


# SEO Related
google_site_verification :
bing_site_verificationÂ  Â :
alexa_site_verificationÂ  :
yandex_site_verification :


# Social Sharing
twitter:
Â  usernameÂ  Â  Â  Â  Â  Â  Â  Â : &twitter
facebook:
Â  usernameÂ  Â  Â  Â  Â  Â  Â  Â :
Â  app_idÂ  Â  Â  Â  Â  Â  Â  Â  Â :
Â  publisherÂ  Â  Â  Â  Â  Â  Â  :
og_imageÂ  Â  Â  Â  Â  Â  Â  Â  Â :Â  # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
Â  typeÂ  Â  Â  Â  Â  Â  Â  Â  Â  Â : # Person or Organization (defaults to Person)
Â  nameÂ  Â  Â  Â  Â  Â  Â  Â  Â  Â : # If the user or organization name differs from the site's name
Â  links: # An array of links to social media profiles


# Analytics
analytics:
Â  providerÂ  Â  Â  Â  Â  Â  Â  Â :Â  "false" # false (default), "google", "google-universal", "google-analytics-4", "custom"
Â  google:
Â  Â  tracking_idÂ  Â  Â  Â  Â  :


# Reading Files
include:
Â  - .htaccess
Â  - _pages
Â  - files
exclude:
Â  - "*.sublime-project"
Â  - "*.sublime-workspace"
Â  - .asset-cache
Â  - .bundle
Â  - .github
Â  - .jekyll-assets-cache
Â  - .sass-cache
Â  - assets/js/_main.js
Â  - assets/js/plugins
Â  - assets/js/vendor
Â  - CHANGELOG
Â  - Capfile
Â  - config
Â  - Dockerfile
Â  - Gemfile
Â  - Gruntfile.js
Â  - gulpfile.js
Â  - LICENSE
Â  - local
Â  - log
Â  - node_modules
Â  - package.json*
Â  - Rakefile
Â  - README
Â  - tmp
Â  - vendor
keep_files:
Â  - .git
Â  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
Â  input: GFM
Â  hard_wrap: false
Â  auto_ids: true
Â  footnote_nr: 1
Â  entity_output: as_char
Â  toc_levels: 1..6
Â  smart_quotes: lsquo,rsquo,ldquo,rdquo
Â  enable_coderay: false


# These settings control the types of collections used by the template
collections:
Â  teaching:
Â  Â  output: true
Â  Â  permalink: /:collection/:path/
Â  publications:
Â  Â  output: true
Â  Â  permalink: /:collection/:path/
Â  portfolio:
Â  Â  output: true
Â  Â  permalink: /:collection/:path/
Â  talks:
Â  Â  output: true
Â  Â  permalink: /:collection/:path/


# These settings control how pages and collections are included in the site
defaults:
Â  # _posts
Â  - scope:
Â  Â  Â  path: ""
Â  Â  Â  type: posts
Â  Â  values:
Â  Â  Â  layout: single
Â  Â  Â  author_profile: true
Â  Â  Â  read_time: true
Â  Â  Â  comments: true
Â  Â  Â  share: true
Â  Â  Â  related: true
Â  # _pages
Â  - scope:
Â  Â  Â  path: ""
Â  Â  Â  type: pages
Â  Â  values:
Â  Â  Â  layout: single
Â  Â  Â  author_profile: true
Â  # _teaching
Â  - scope:
Â  Â  Â  path: ""
Â  Â  Â  type: teaching
Â  Â  values:
Â  Â  Â  layout: single
Â  Â  Â  author_profile: true
Â  Â  Â  share: true
Â  Â  Â  comments: true
Â  # _publications
Â  - scope:
Â  Â  Â  path: ""
Â  Â  Â  type: publications
Â  Â  values:
Â  Â  Â  layout: single
Â  Â  Â  author_profile: true
Â  Â  Â  share: true
Â  Â  Â  comments: true
Â  # _portfolio
Â  - scope:
Â  Â  Â  path: ""
Â  Â  Â  type: portfolio
Â  Â  values:
Â  Â  Â  layout: single
Â  Â  Â  author_profile: true
Â  Â  Â  share: true
Â  Â  Â  comment: true
Â  # _talks
Â  - scope:
Â  Â  Â  path: ""
Â  Â  Â  type: talks
Â  Â  values:
Â  Â  Â  layout: talk
Â  Â  Â  author_profile: true
Â  Â  Â  share: true


# Sass/SCSS
sass:
Â  sass_dir: _sass
Â  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
timezone: Etc/UTC # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins
plugins:
Â  - jekyll-feed
Â  - jekyll-gist
Â  - jekyll-paginate
Â  - jekyll-sitemap
Â  - jekyll-redirect-from
Â  - jemoji

# Mimic GitHub Pages with --safe
whitelist:
Â  - jekyll-feed
Â  - jekyll-gist
Â  - jekyll-paginate
Â  - jekyll-sitemap
Â  - jekyll-redirect-from
Â  - jemoji


# Archives
#Â  Type
#Â  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#Â  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#Â  Path (examples)
#Â  - Archive page should exist at path when using Liquid method or you can
#Â  Â  expect broken links (especially with breadcrumbs enabled)
#Â  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#Â  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#Â  - <base_path/my-awesome-category/index.html ~> path: /
category_archive:
Â  type: liquid
Â  path: /categories/
tag_archive:
Â  type: liquid
Â  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#Â  Â enabled:
#Â  Â  Â - categories
#Â  Â  Â - tags
#Â  Â layouts:
#Â  Â  Â category: archive-taxonomy
#Â  Â  Â tag: archive-taxonomy
#Â  Â permalinks:
#Â  Â  Â category: /categories/:name/
#Â  Â  Â tag: /tags/:name/


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
Â  clippings: all
Â  ignore:
Â  Â  envs: development
